Freshen maintainer scripts.

diff --git a/debian/prerm b/debian/prerm
--- a/debian/prerm
+++ b/debian/prerm
@@ -1,14 +1,37 @@
 #!/bin/sh
+# prerm script for argus-clients
+#
+# see: dh_installdeb(1)
+
 set -e
-#
-# stop the daemon before uninstall
-#
-if [ -x "/etc/init.d/radium" ]; then
-	invoke-rc.d radium stop || exit $?
-fi
-if [ -x "/etc/init.d/rasplit" ]; then
-	invoke-rc.d rasplit stop || exit $?
-fi
+
+# summary of how this script can be called:
+#        * <prerm> `remove'
+#        * <old-prerm> `upgrade' <new-version>
+#        * <new-prerm> `failed-upgrade' <old-version>
+#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
+#        * <deconfigured's-prerm> `deconfigure' `in-favour'
+#          <package-being-installed> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+
+case "$1" in
+    remove|upgrade|deconfigure)
+    ;;
+
+    failed-upgrade)
+    ;;
+
+    *)
+        echo "prerm called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
 #DEBHELPER#
 
